### ISSUE TITLE
cmmmu

### ISSUE THREAD

**Issue by phellonchen** [EvolvingLMMs-Lab/lmms-eval#10]
when using '--tasks cmmmu' I got some wrongs.

assert tasks != [], "No tasks specified, or no tasks found. Please verify the task names.

**Comment by kcz358** [comment]
Hi, when I tried `lmms_eval --tasks list`, I can see cmmmu on the list and this means cmmmu can be loaded successfully.

<img width="453" alt="image" src="https://github.com/EvolvingLMMs-Lab/lmms-eval/assets/92624596/bc77bfc7-33f0-4a91-8db5-09e8e578487c">

If you are encountering this issue, maybe you can try `lmms_eval --tasks list --verbosity DEBUG` and see what error causing  the tasks can not be loaded.

**Comment by kcz358** [comment]
@phellonchen 

I haven't tried this but based on my understanding of the code and huggingface `load_dataset` api. 

You may want to change the `dataset_path` in the [_default_template_cmmmu_yaml](https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/main/lmms_eval/tasks/cmmmu/_default_template_cmmmu_yaml) to your local dataset path. 

Our code loads huggingface dataset using the `load_dataset` method. For each tasks, the code logic is like this `dataset = load_dataset(<dataset_path>, name = <dataset_name> (if there is one else None for this), split = <split>)`. Thus, as long as you clone our dataset repo and can successfully load the dataset through `load_dataset` method, this should be able to work.
