### ISSUE TITLE
BUG: when I test mme  on internvl2, an error will occur：'InternVL2' object has no attribute 'accelerator'

### ISSUE THREAD

**Issue by daixiangzi** [EvolvingLMMs-Lab/lmms-eval#152]
```
CUDA_VISIBLE_DEVICES="7"  accelerate launch \
    --num_processes=1 \
    --main_process_port 12348 \
    -m lmms_eval \
    --model internvl2 \
    --model_args pretrained="OpenGVLab/InternVL2-8B,device_map=auto" \
    --tasks mme \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix llava_mme \
    --output_path ./logs/
```
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/bd9908fb714552a00385d662f2b9b43c752f46dc/lmms_eval/models/internvl2.py#L180
lm model have't  **self.accelerator = accelerato**r, but **lm.accelerator.num_processes** attribute will appear in  evaluator.py,
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/bd9908fb714552a00385d662f2b9b43c752f46dc/lmms_eval/evaluator.py#L639

**Comment by kcz358** [comment]
Oh, I think we forgot to add the `self.accelerator` when num_process is equal to 1. I will fix it later

**Comment by skyil7** [comment]
I think we can close this issue since @kcz358 fixed it.

https://github.com/EvolvingLMMs-Lab/lmms-eval/commit/1703b02ed66e06636929f213156c82e392ea3fd6

**Comment by daixiangzi** [comment]
> I think we can close this issue since @kcz358 fixed it.
> 
> [1703b02](https://github.com/EvolvingLMMs-Lab/lmms-eval/commit/1703b02ed66e06636929f213156c82e392ea3fd6)

yes
