### ISSUE TITLE
 Where should this function `loglikelihood` be called?

### ISSUE THREAD

**Issue by liguopeng0923** [EvolvingLMMs-Lab/lmms-eval#177]
Hi,

I tried to apply your framework for my model, but I don't know  where should this function `loglikelihood` be called?

**Comment by kcz358** [comment]
Hi @liguopeng0923 , `loglikelihood` is a function to be used for calculating scores such as perplexity or used for answering multi-choice questions. You can check tasks such as seedbench, worldqa, and perception_test that use this forward function. Most of the tasks do not require this forward function and are generation based. So if you are not going to test your model on these kind of tasks then would be fine to use a dummy function for it.

**Comment by liguopeng0923** [comment]
Thanks! I got it!
