### ISSUE TITLE
Module 'exact_match' doesn't exist on the Hugging Face Hub either.

### ISSUE THREAD

**Issue by xienan0326** [EvolvingLMMs-Lab/lmms-eval#18]
install:
pip install lmms-eval

run:
accelerate launch --num_processes=8 -m lmms_eval --model llava   --model_args pretrained="liuhaotian/llava-v1.5-7b"   --tasks mme  --batch_size 1 --log_samples --log_samples_suffix llava_v1.5_mme --output_path ./logs/

bug:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/lmms_eval/__main__.py", line 24, in <module>
    from lmms_eval import evaluator, utils
  File "/usr/local/lib/python3.10/dist-packages/lmms_eval/evaluator.py", line 17, in <module>
    import lmms_eval.api.metrics
  File "/usr/local/lib/python3.10/dist-packages/lmms_eval/api/metrics.py", line 146, in <module>
    exact_match = evaluate.load("exact_match")
  File "/usr/local/lib/python3.10/dist-packages/evaluate/loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/evaluate/loading.py", line 681, in evaluation_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at /exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.

**Comment by kcz358** [comment]
Hi, may I asked have you installed llava from github also? I did not encounter any issue using the same command. You may want to check if flash-attn and llava are both installed.

**Comment by xienan0326** [comment]
> llava

yeah，pip install package or pip install -e . Tried both installation methods 
flash-attn and llava are both installed.
What else do I need to check?
![image](https://github.com/EvolvingLMMs-Lab/lmms-eval/assets/38122102/0a74dc3b-2733-4af9-b5cb-458fc695681c)

**Comment by xienan0326** [comment]
> Hi, may I asked have you installed llava from github also? I did not encounter any issue using the same command. You may want to check if flash-attn and llava are both installed.

Expect reply

**Comment by xienan0326** [comment]
> Hi, may I asked have you installed llava from github also? I did not encounter any issue using the same command. You may want to check if flash-attn and llava are both installed.

yeah，pip install package or pip install -e . Tried both installation methods
flash-attn and llava are both installed.
What else do I need to check?
![image](https://github.com/EvolvingLMMs-Lab/lmms-eval/assets/38122102/b12a77a3-d4ad-4d45-81a9-887b1334d77d)

**Comment by kcz358** [comment]
Hmm... , This is interesting. Mine works perfectly fine under the same environment.

Can you provide the whole running log of your program? @xienan0326 

Maybe need to see where the error occurs. Is it before model responding or postprocessing.

**Comment by lucasjinreal** [comment]
Same error

/exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.


I would suggest try test your script on more robust envirment, this is hard to debug, it evolves logic inside.

**Comment by xienan0326** [comment]
> Same error
> 
> /exact_match/exact_match.py. Module 'exact_match' doesn't exist on the Hugging Face Hub either.
> 
> I would suggest try test your script on more robust envirment, this is hard to debug, it evolves logic inside.
手动配置下可以，但是又遇到了如何加载本地数据的问题
https://huggingface.co/spaces/evaluate-metric/exact_match

**Comment by zyp2** [comment]
请问下，我这边也是遇到了同类问题，该如何解决，有解决方案吗

**Comment by liguopeng0923** [comment]
我也是同样的问题

**Comment by kcz358** [comment]
Hi @zyp2 @liguopeng0923 , you can refer to #75 , hope it would help

**Comment by liguopeng0923** [comment]
Hi @kcz358 ,

I have solved it by installing the offline `extract_math` in `llms-eval`.

But I met new issues
<img width="605" alt="image" src="https://github.com/user-attachments/assets/2cae80c5-6556-4e56-8eb0-2f603073750f">

**Comment by kcz358** [comment]
@liguopeng0923 , I think it is just nltk download issue for nextqa. I think the evaluation will still work if you are not evaluating on nextqa

**Comment by liguopeng0923** [comment]
Hi @kcz358 ,

Actually, I find some other datasets also have this problem, such as `detailcaps`.

Why I need to load all json files if I only evaluate on one dataset.

**Comment by kcz358** [comment]
Hi @liguopeng0923 , because we need to initialize all the tasks and then select the task you want to evaluate from the `TASK_REGISTRY`. If you don't want to see the error message, you can simply delete the folder or the yaml file if you won't need this task.

**Comment by liguopeng0923** [comment]
Thanks. But I find the reason is the following code is not robust. For example, my machine cannot download packages from the internet and I download the offline package. But the following code still requests the internet.
<img width="903" alt="image" src="https://github.com/user-attachments/assets/cd4106a2-4c33-4b62-9a3c-d77b74a698c6">
