### ISSUE TITLE
Missing MMU-mv-test in llava-interleave-bench

### ISSUE THREAD

**Issue by liguopeng0923** [EvolvingLMMs-Lab/lmms-eval#216]
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/483e1d20-d4a4-432d-9ae3-2a64b684c96d">

I find the current eval results missing the `mmmu-mv`

<img width="351" alt="image" src="https://github.com/user-attachments/assets/3e83fe59-e6f9-4613-9313-cad910b030fe">

**Comment by Luodian** [comment]
You may need to contact the authors. They report it based on MMMU's original evaluation and filtering the multi-images part to calculate a specific accuracy.

**Comment by liguopeng0923** [comment]
Thank you for your timely reply!
