### ISSUE TITLE
How to check detailed results for benchmarks, like VideoMME?

### ISSUE THREAD

**Issue by John-Ge** [EvolvingLMMs-Lab/lmms-eval#225]
Before you open an issue, please check if a similar issue already exists or has been closed before.

- [x] A descriptive title:
- [x] A detailed description

Thank you for your contributions!

Benchmarks, like VideoMME, have many categories of tasks. How could we check the results for each task and results for their predefined video length? I find that such results are not in the result.json and videomme.json files. 

Thank you!

**Comment by zhang9302002** [comment]
Hello,
I have the same concern. Could you tell me how did you solve this problem?
