### ISSUE TITLE
How to load dataset in offline mode?

### ISSUE THREAD

**Issue by pipixin321** [EvolvingLMMs-Lab/lmms-eval#23]
Since my server can't access huggingface.co, how can I load dataset from local direction?
Thank you for your contributions!

**Comment by kcz358** [comment]
Hi, you can refer to

#15 and #21

**Comment by pipixin321** [comment]
Thanks, I solve this problem by defining `loca_dir` in `lmms-eval/lmms_eval/api/task.py line.528`
```python
self.DATASET_PATH = os.path.join(local_dir, self.config.dataset_path)
```
