### ISSUE TITLE
[Question] Does the collator reflect the vision token well?

### ISSUE THREAD

**Issue by abzb1** [EvolvingLMMs-Lab/lmms-eval#267]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### When you open an issue, please be sure to include the following

- [x] A descriptive title: [xxx] XXXX
- [x] A detailed description

Thank you for your contributions!

#### Title and content are the same
Does the collator reflect the vision token well?

`lm eval harness` only focuses on text tokens, which allows the collator to effectively detect Out-of-Memory (OOM) errors related to text processing.
However, in `lmms-eval`, the handling of vision tokens varies across different models.
And it's unclear whether the collator currently takes into account the memory requirements associated with vision tokens.

In my experience, I encountered OOM errors on sample 76 out of 1500 while using a single GPU (A6000).
This suggests a potential discrepancy between the collator's re-ordering and the actual memory usage ranking when dealing with vision tokens.
It would be beneficial to clarify how the collator manages vision tokens and whether it accurately reflects their memory footprint in the context of `lmms-eval`.

**Comment by kcz358** [comment]
The collator does not count the visual tokens as visual tokens are counted in different way in different models so it is hard to make a unified collator across different models.

**Comment by abzb1** [comment]
At first glance, it seems like it would be possible to at least utilize the shape of the image to order reqs.

**Comment by kcz358** [comment]
Yeah it is possible, but since most of our model are inferencing using single batch so we haven't looked deeply into it
