### ISSUE TITLE
Not Support LLava 1.6or llava-Next?

### ISSUE THREAD

**Issue by BlueBlueFF** [EvolvingLMMs-Lab/lmms-eval#3]
it seems this git repo depends on LLava Repo, but the LLava repo not support LLava 1.6 Eval right row? How to eval this model?(such as multi image patch feature in LLava-Next/1.6)

**Comment by kcz358** [comment]
Hi, we currently support LLaVA 1.6 model for eval. To do so, you just need to clone the newest LLaVA repo (which already updated for 1.6) and `pip install -e .` for dependency. Then you can simply pass `model_args pretrained="liuhaotian/llava-v1.6-mistral-7b"` to do evaluation on LLaVA-1.6.

**Comment by BlueBlueFF** [comment]
> Hi, we currently support LLaVA 1.6 model for eval. To do so, you just need to clone the newest LLaVA repo (which already updated for 1.6) and `pip install -e .` for dependency. Then you can simply pass `model_args pretrained="liuhaotian/llava-v1.6-mistral-7b"` to do evaluation on LLaVA-1.6.

Are we support for this https://huggingface.co/liuhaotian/llava-v1.6-34b ?

**Comment by Luodian** [comment]
yes it's supported. You could see Readme.MD We updated the scripts for running 34B model with correct 'conv_template=mistral_direct'
