### ISSUE TITLE
Evaluation of Qwen2VL-7B OOM

### ISSUE THREAD

**Issue by Na-nata** [EvolvingLMMs-Lab/lmms-eval#436]
When using lmmseval for the evaluation of qwen2VL-7B, I always run out of memory. Below is my evaluation script. Is there any way to solve this problem?
<img width="1826" alt="image" src="https://github.com/user-attachments/assets/a8fcf71d-1815-4359-b2c9-3d37eb3e7b7b">
`TASK=ocrbench 
CKPT_PATH=/model_weight/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/51c47430f97dd7c74aa1fa6825e68a813478097f
python3 -m accelerate.commands.launch \
    --num_processes=8 \
    -m lmms_eval \
    --model qwen2_vl \
    --model_args pretrained=$CKPT_PATH \
    --tasks $TASK \
    --batch_size 1 \
    --log_samples \
    --log_samples_suffix $TASK \
    --output_path ./Qwen2VL/eval_$TASK
~                                       `

**Comment by Luodian** [comment]
the major issue of Qwen2-VL is the max_pixels, it's default is `16384 * 28 * 28` (28x28 each token, 16384 max tokens), you can set this to a very small number like `256 * 28 * 28` to see if OOM still exists. And then gradually increase it to a bearable threshold.

https://github.com/kq-chen/qwen-vl-utils/blob/fdefae03a8dfee0ec11274b77437db8951eb67fd/src/qwen_vl_utils/vision_process.py#L17

**Comment by Na-nata** [comment]
thanku sooooooooo much! it works!!!
