### ISSUE TITLE
How to self define my own text prompt when using lmms-eval?

### ISSUE THREAD

**Issue by pengzhansun** [EvolvingLMMs-Lab/lmms-eval#440]
I am trying to run some experiments on qwen2-VL REC task, I tried to use --system_instruction to change the text prompt, however, it was simply added before the default text prompt, instead of replace the default prompt with the newly self-defined system_instruction. Can you help to clarify to make things easier? Thank you so much!

**Comment by Man-PaperRejected** [comment]
hello, have you found where to set the prompt?
