### ISSUE TITLE
Bug: Llava One Vision is failing on subclasses of PIL.Image

### ISSUE THREAD

**Issue by elronbandel** [EvolvingLMMs-Lab/lmms-eval#462]
When sending an Image that is a sub class of `PIL.Image.Image` this condition is not satisfied:
https://github.com/EvolvingLMMs-Lab/lmms-eval/blob/d8f1f9cf7ad824b8b5315ab6fafb8768fb4345d6/lmms_eval/models/llava_onevision.py#L282
It should have `isinstance(visual[0], PIL.Image.Image)`.

**Comment by pufanyi** [comment]
Hello! Thanks for your issue. I have created a PR in #472
