### ISSUE TITLE
Model will be loaded on different devices when using multiple gpus.

### ISSUE THREAD

**Issue by baichuanzhou** [EvolvingLMMs-Lab/lmms-eval#67]
It appears that models will be loaded on different gpus when setting `num_processes` to more than one, which will cause error:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`

Here's my command to launch:
```
accelerate launch --num_processes=2 -m lmms_eval --model llava   --model_args pretrained="xxx,conv_template=xxx"   --tasks gqa,vqav2,scienceqa,textvqa --batch_size 1 --log_samples --log_samples_suffix xxx --output_path ./logs/
```

I found a temporary fix by installing previous version:
`pip install git+https://github.com/EvolvingLMMs-Lab/lmms-eval.git@bf4c78b7e405e2ca29bf76f579371382fec3dd02`
and in this version multi-gpu inference works fine.

**Comment by kcz358** [comment]
May I ask in which line of inference did this error occur?

**Comment by baichuanzhou** [comment]
Sorry for the delay.

Here is one error message:
```
ERROR Error Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution) in generating
```

**Comment by kcz358** [comment]
You might also want to try setting device_map=auto in your model_args when you do multi-processing

`--model_args pretrained=xxx,conv_template=xxx,device_map=auto`

**Comment by kcz358** [comment]
Sorry, my bad

Should set `device_map=""` when using multiprocess. Set `device_map=auto` only when you use num_processes=1
