### ISSUE TITLE
Typo in results sheet for llava-v1.6-vicuna-7b

### ISSUE THREAD

**Issue by FGiuliari** [EvolvingLMMs-Lab/lmms-eval#8]
Hello, nice work on the benchmark.

I noticed a typo in the results sheet.
Cell J2 says "1.6-13B (lmms-eval)" but the details expressed in cell j3 says that it is vicuna 7B, not 13B.

**Comment by pufanyi** [comment]
Hello! We have fixed the sheet. Thank you so much!
