### ISSUE TITLE
Prompt for MathVista

### ISSUE THREAD

**Issue by yqy2001** [EvolvingLMMs-Lab/lmms-eval#90]
I noticed that there are several kinds of prompts for MathVista. Which one is used for the reported number of LLaVA-NeXT? Thank you.

![image](https://github.com/EvolvingLMMs-Lab/lmms-eval/assets/55196500/854d65f2-6d8f-411b-b3e8-3c22584f04bd)

**Comment by Luodian** [comment]
We use the `default` for llava-next.

**Comment by yqy2001** [comment]
Got it, Thank you!
