### ISSUE TITLE
Any plan for supporting Lora peft loading

### ISSUE THREAD

**Issue by hxhcreate** [EvolvingLMMs-Lab/lmms-eval#96]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### When you open an issue, please be sure to include the following

- [ ] A descriptive title: [xxx] XXXX
- [ ] A detailed description

Thank you for your contributions!

**Comment by Luodian** [comment]
Yes! I think this would not be hard since LLaVA naturally support it. But for other models, should write customized loading process.

Basically, it's a model side change, `lmms-eval` only provide the interfaces for `inputs`, `outputs` and calculate scores for each task.
